trigger: none
pr: none

variables:
  terraformVersion: '1.14.8'
  ARM_CLIENT_ID: '973195d4-9965-4184-b8ec-0deb89d4d67e'
  ARM_SUBSCRIPTION_ID: '79bdf282-66fa-4bdc-b5dc-5f029b9647de'
  ARM_TENANT_ID: 'df65ce47-b9d7-4489-9610-3ea8b8385565'
  ARM_CLIENT_SECRET: 'Svl8Q~gcnPA-4X6FHqjiWVmJkcqwz78zykXPKcLl'
  workingDirectory: '$(System.DefaultWorkingDirectory)/'

stages:
- stage:  Initiliaze 
  displayName: Terraform Init
  jobs:

  - job: TerraformInit
    displayName: Init
    pool:
      name: k8s-selfhosted-agents
    steps:

    - checkout: self

    - task: TerraformInstaller@1
      displayName: Install terraform
      inputs:
        terraformVersion: $(terraformVersion)   

    - script: terraform version 
      displayName: Verify Terraform version

    - script: terraform init
      workingDirectory: $(workingDirectory)
      displayName: terraform init
   
    - script: terraform plan
      workingDirectory: $(workingDirectory)
      displayName: Terraform Plan 
      env:
        ARM_SUBSCRIPTION_ID: var.subcription_id
        ARM_CLIENT_ID: var.client_id
        ARM_CLIENT_SECRET: var.client_secret
        TF_VAR_tenant_id: var.tenant_id
          
    - publish: $(workingDirectory)
      artifact: TerraformPlan
      displayName: publishing Terraform plan

- stage: Approval
  displayName: Approval stage
  dependsOn: Initiliaze

  jobs:

  - job: ManualApproval
    displayName: Manual Approval
    pool:
      name: k8s-selfhosted-agents
    steps:
    - task: ManualValidation@0
      timeoutInMinutes: 1440
      inputs:
        instructions: |
          Terraform plan completed
          please review the output and approve the piplein
        onTimeOut: reject



      




