trigger: none
pr: none

variables:
  terraformVersion: '1.14.8'
  ARM_CLIENT_ID: '973195d4-9965-4184-b8ec-0deb89d4d67e'
  ARM_SUBSCRIPTION_ID: '79bdf282-66fa-4bdc-b5dc-5f029b9647de'
  ARM_TENANT_ID: 'df65ce47-b9d7-4489-9610-3ea8b8385565'
  ARM_CLIENT_SECRET: 'Svl8Q~gcnPA-4X6FHqjiWVmJkcqwz78zykXPKcLl'
  workingDirectory: '$(System.DefaultWorkingDirectory)/'

stages:
- stage:  Initiliaze 
  displayName: Terraform Init
  jobs:

  - job: TerraformInit
    displayName: Init
    pool:
      name: k8s-selfhosted-agents
    steps:

    - checkout: self

    - task: TerraformInstaller@1
      displayName: Install terraform
      inputs:
        terraformVersion: $(terraformVersion)   

    - script: terraform version 
      displayName: Verify Terraform version

    - script: terraform init
      workingDirectory: $(workingDirectory)
      displayName: terraform init
   
    - script: terraform plan
      workingDirectory: $(workingDirectory)
      displayName: Terraform Plan 
      env:
        TF_VAR_subscription_id: $(ARM_SUBSCRIPTION_ID)
        TF_VAR_client_id: $(ARM_CLIENT_ID)
        TF_VAR_client_secret: $(ARM_CLIENT_SECRET)
        TF_VAR_tenant_id: $(ARM_TENANT_ID)
          
    - publish: $(workingDirectory)
      artifact: TerraformPlan
      displayName: publishing Terraform plan




